name: pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: build our shit
        run: ./ssg -i resources.json -o resources.html
      - name: make our output tar
        run: tar cvf out.tar resources.html
      - name: gzip the tar
        run: gzip out.tar

      - name: upload the artifact
        uses: actions/upload-artifact@v4.3.6
        with:
          name: github-pages
          path: out.tar.gz
          if-no-files-found: error
          overwrite: true
