name: pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: do i really have to name this
        run: mkdir out

      - name: build our shit
        run: ./ssg -i resources.json -o out/index.html

      - name: yeah
        run: cp assets/* out/

      - name: you can tell what this does
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          force_orphan: true
          commit_message:
